stages:
  - build
  - increase-version
  - deploy-baget

variables:
  PROJECT_DIRECTORY: "Wkg.EntityFrameworkCore.Oracle/Wkg.EntityFrameworkCore.Oracle"
  PROJECT_FILE_PATH: "${PROJECT_DIRECTORY}/Wkg.EntityFrameworkCore.Oracle.csproj"
  MAJOR_VERSION: "9"
  MINOR_VERSION: "0"

include:
  - project: 'wkg/gitlab-templates'
    ref: 'v1.2.19'
    file:
      - '/jobs/build_dotnet_9.yml'
      - '/jobs/increase_version.yml'
      - '/jobs/deploy_nuget_dotnet_9.yml'

build:
  extends: .build

increase-version:
  extends: .increase-version
  only:
    - main
    - master
    - /^rc-.*$/
    - /^dev-.*$/ 
    - /^diag-.*$/

deploy:
  extends: .deploy-nuget-public
  variables:
    DOTNET_CI_VERSION_FILE: "${PROJECT_DIRECTORY}/WkgEntityFrameworkCoreOracle.cs"
