stages:
    - build
    - test
    - increase-version
    - deploy-baget

variables:
    PROJECT_FILE_PATH: "Wkg.EntityFrameworkCore.Oracle/Wkg.EntityFrameworkCore.Oracle/Wkg.EntityFrameworkCore.Oracle.csproj"
    MAJOR_VERSION: "7"
    MINOR_VERSION: "1"

include:
    - project: 'wkg/gitlab-templates'
      ref: 'v1.1.0'
      file:
          - '/jobs/build_dotnet_7.yml'
          - '/jobs/test_dotnet_7.yml'
          - '/jobs/increase_version.yml'
          - '/jobs/deploy_baget_dotnet_7.yml'

build:
    extends: .build

test:
    extends: .test

increase-version:
    extends: .increase-version

deploy:
    extends: .deploy-baget        